apiVersion: v1
kind: Service
metadata:
  labels:
    app: trex
  name: trex
  namespace: benchmark
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 4500
    protocol: TCP
    targetPort: 4501
    name: publisher
  - port: 4501
    protocol: TCP
    targetPort: 4501
    name: rpc
  selector:
    app: trex
  sessionAffinity: None
  type: ClusterIP
