apiVersion: v1
kind: Pod
metadata:
  name: trex
  namespace: benchmark
  annotations:
    cpu-load-balancing.crio.io: "disable"
    cpu-quota.crio.io: "disable"
    irq-load-balancing.crio.io: "disable"
  labels:
    app: trex
spec:
  runtimeClassName: performance-openshift-node-performance-profile
  restartPolicy: Never
  containers:
  - name: trex
    image: quay.io/dosman/trex:3.02
    command: ["/usr/bin/run.sh"]
    imagePullPolicy: Always
    env:
    - name: SRIOV_ID_A
      value: "PF_FH"
    - name: SRIOV_ID_B
      value: "PF_MH"
    - name: PCIDEVICE_OPENSHIFT_IO_PF_FH
      value: "0000:1a:00.2"
    - name: PCIDEVICE_OPENSHIFT_IO_PF_MH
      value: "0000:1a:00.3"
    - name: PORT_BANDWIDTH_GB
      value: "25"
    - name: DEVICE_A_MAC
      value: "0xb4,0x96,0x91,0xb4,0xa6,0xb2"
    - name: DEVICE_B_MAC
      value: "0xb4,0x96,0x91,0xb4,0xa6,0xb3"
    - name: DEVICE_A_PEER_MAC
      value: "0x60,0x0,0x0,0x0,0x0,0x1"
    - name: DEVICE_B_PEER_MAC
      value: "0x60,0x0,0x0,0x0,0x0,0x2"
    securityContext:
      runAsUser: 0
      privileged: true
      capabilities:
        add: ["IPC_LOCK","SYS_ADMIN","SYS_NICE", "NET_RAW", "SYS_RESOURCE", "SYS_RAWIO"]
    resources:
      limits:
        cpu: 6
        memory: "1Gi"
        hugepages-1Gi: "8Gi"
      requests:
        cpu: 6
        memory: "1Gi"
        hugepages-1Gi: "8Gi"
    volumeMounts:
    - name: hugepages
      mountPath: /mnt/huge
    - name: dpdk
      mountPath: /var/run/dpdk
    - name: modules
      mountPath: /lib/modules
    - name: firmware
      mountPath: /lib/firmware
    - name: vfio
      mountPath: /dev/vfio
      readOnly: False
  terminationGracePeriodSeconds: 5
  volumes:
  - name: firmware
    hostPath:
      path: /lib/firmware
  - name: modules
    hostPath:
      path: /lib/modules
  - name: hugepages
    emptyDir:
      medium: HugePages
  - name: dpdk
    emptyDir: {}
  - name: vfio
    hostPath:
      path: /dev/vfio
      type: Directory
