apiVersion: v1
kind: Pod
metadata:
  name: testpmd
  namespace: benchmark
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {
       "name": "sriov-nw-du-fh",
       "mac": "60:00:00:00:00:01",
       "namespace": "openshift-sriov-network-operator"
      },
      {
       "name": "sriov-nw-du-mh",
       "mac": "60:00:00:00:00:02",
       "namespace": "openshift-sriov-network-operator"
      }
    ]'
    cpu-load-balancing.crio.io: "disable"
    cpu-quota.crio.io: "disable"
    irq-load-balancing.crio.io: "disable"
  labels:
    app: testpmd
spec:
  runtimeClassName: performance-openshift-node-performance-profile
  restartPolicy: Never
  containers:
  - name: testpmd
    image: quay.io/dosman/dpdk-testpmd:22.11.1
    imagePullPolicy: Always
    env:
    - name: SRIOV_ID_A
      value: "DU_FH"
    - name: SRIOV_ID_B
      value: "DU_MH"
    - name: FORWARD_MODE
      value: "mac"
    securityContext:
      runAsUser: 0
      capabilities:
        add: ["IPC_LOCK","SYS_ADMIN","SYS_NICE", "NET_RAW", "SYS_RESOURCE"]
    resources:
      limits:
        cpu: 4
        memory: "1Gi"
        hugepages-1Gi: "4Gi"
      requests:
        cpu: 4
        memory: "1Gi"
        hugepages-1Gi: "4Gi"
    volumeMounts:
    - mountPath: /mnt/huge
      name: hugepages
    - name: dpdk
      mountPath: /var/run/dpdk
  volumes:
  - name: hugepages
    emptyDir:
      medium: HugePages
  - name: dpdk
    emptyDir: {}
